### PR TITLE
Added screenshot taker in python

### PR DESCRIPTION
**Pull request by prathimacode-hub**
This project helps in taking the screenshot of the page we are in.

It's a useful daily task done on regular intervals.

### CODE REVIEW

**Review by fackid1 — APPROVED** [review]
Nice one Prathima! Keep it up

**Comment by coffee-tonight** [comment]
`<h3 style="background:#00963e44; ">Very well done Prathima<\h3>`

**Comment by coffee-tonight** [comment]
Thanks Prathima for your contribution.

**Comment by prathimacode-hub** [comment]
Most welcome, thank you for providing this opportunity. 👍@coffee-tonight

**Pull request merged**
